### ISSUE TITLE
Fabric migration

### ISSUE THREAD

**Issue by GZLiew** [razorRun/react-native-vlc-media-player#149]
any plans to update this library to support TurboModules?

**Comment by Duell10111** [comment]
Additionally we could think of migrating to Swift and Kotlin?

**Comment by razorRun** [comment]
Happy to support if anyone wants to take charge 😉. More than happy to add to the repo if anyone likes to maintain it as I don’t get dev time as I used to

**Comment by 1280103995** [comment]
I made this work but iOS doesn't work on old RN architecture (I'm not good at iOS). Also, it seems that rtsp doesn't work. It would be great if someone can help test it.  https://github.com/1280103995/react-native-vlc-media-player/tree/main

The reason I'm doing this is because I need it to play rtsp.
