### ISSUE TITLE
Doesn't work with local videos

### ISSUE THREAD

**Issue by Arekjaar4** [razorRun/react-native-vlc-media-player#160]
I'm testing the latest versions of the library and it works correctly with online videos, but it doesn't work with videos stored locally.

**Comment by notjulian** [comment]
Hi,
can you please post you uri?

es.

```
const fileName = `${RNFS.DocumentDirectoryPath}/video.mp4`
this.setState({localUri: fileName});
// then in render ...

<VLCPlayer
          style={{width: '100%', height: 250}}
          autoAspectRatio={true}
          videoAspectRatio={`${windowWidth}:258`}
          autoplay={true}
          onProgress={() => {
            console.log('onProgress')
          }}

          source={{
            uri: this.state.localUri,
          }}
        />
```

**Comment by subramani01** [comment]
Just letting people know who comes to see this issue, local videos are working fine.

**Comment by SarangGit** [comment]
If local file path starts with "file://"  the please remove "file://" from the path and pass the remaining string in the player uri. It will work. 

e.g 

initial filePath : file:///data/user/0/temp_82c6f5b7-88c6-4d04-95b0-d6647f03b13a.mp4

Final path : /data/user/0/temp_82c6f5b7-88c6-4d04-95b0-d6647f03b13a.mp4 

Because in the code VLCPlayer.js code is appending "file://" in the uri

 let uri = source.uri || "";
  if (uri && uri.match(/^\//)) {
    uri = `file://${uri}`;
  }
