### ISSUE TITLE
Long video load time

### ISSUE THREAD

**Issue by lightninglu10** [razorRun/react-native-vlc-media-player#181]
Trying to load local videos, it takes a long time for the video to instantiate on debug mode. An 11s video takes over 20-30s to load up initially. Is there something we're doing wrong here?

**Comment by reubber** [comment]
I don't know the reason, but it seems to have **worked** here after disabling the app's _local network_, while on other devices, enabling this option makes the video load quickly.

**Comment by reubber** [comment]
> Trying to load local videos, it takes a long time for the video to instantiate on debug mode. An 11s video takes over 20-30s to load up initially. Is there something we're doing wrong here?

I don't know the reason, but it seems to have worked here after disabling the app's local network, while on other devices, enabling this option makes the video load quickly.

**Comment by AnZuev** [comment]
Hi
I had the same issue. It was fixed by enabling "com.apple.developer.networking.multicast" capability.
It is not an ordinary capability, you must get approved by Apple.  You can do it here https://developer.apple.com/contact/request/networking-multicast. For me it took less than a week to get approved for both of my apps.

Initially I have found it on VLC forum https://code.videolan.org/videolan/VLCKit/-/issues/703

Hope it helps
